SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PREREQUISITE'
AND CONSTRAINT_TYPE = 'R';
ALTER TABLE PREREQUISITE
DROP CONSTRAINT SYS_C008;
ALTER TABLE COURSE
RENAME COLUMN Course_number TO CID;
DESC COURSE;