CREATE TABLE STUDENT (
    Name VARCHAR2(30),
    Student_number NUMBER,
    Class NUMBER,
    Major VARCHAR2(20)
);

CREATE TABLE COURSE (
    Course_name VARCHAR2(50),
    Course_number VARCHAR2(10),
    Credit_hours NUMBER,
    Department VARCHAR2(20)
);

CREATE TABLE SECTION (
    Section_identifier NUMBER,
    Course_number VARCHAR2(10),
    Semester VARCHAR2(20),
    Year NUMBER,
    Instructor VARCHAR2(30)
);

CREATE TABLE GRADE_REPORT (
    Student_number NUMBER,
    Section_identifier NUMBER,
    Grade CHAR(1)
);

CREATE TABLE PREREQUISITE (
    Course_number VARCHAR2(10),
    Prerequisite_number VARCHAR2(10)
);

INSERT INTO STUDENT VALUES ('Smith',17,1,'CS');
INSERT INTO STUDENT VALUES ('Brown',8,2,'CS');

INSERT INTO COURSE VALUES ('Intro to Computer Science','CS1310',4,'CS');
INSERT INTO COURSE VALUES ('Data Structures','CS3320',4,'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics','MATH2410',3,'MATH');
INSERT INTO COURSE VALUES ('Database','CS3380',3,'CS');

INSERT INTO SECTION VALUES (85,'MATH2410','Fall',7,'King');
INSERT INTO SECTION VALUES (92,'CS1310','Fall',7,'Anderson');
INSERT INTO SECTION VALUES (102,'CS3320','Spring',8,'Knuth');
INSERT INTO SECTION VALUES (112,'MATH2410','Fall',8,'Chang');
INSERT INTO SECTION VALUES (119,'CS1310','Fall',8,'Anderson');
INSERT INTO SECTION VALUES (135,'CS3380','Fall',8,'Stone');

INSERT INTO GRADE_REPORT VALUES (17,112,'B');
INSERT INTO GRADE_REPORT VALUES (17,119,'C');
INSERT INTO GRADE_REPORT VALUES (8,85,'A');
INSERT INTO GRADE_REPORT VALUES (8,92,'A');
INSERT INTO GRADE_REPORT VALUES (8,102,'B');
INSERT INTO GRADE_REPORT VALUES (8,135,'A');

INSERT INTO PREREQUISITE VALUES ('CS3380','CS3320');
INSERT INTO PREREQUISITE VALUES ('CS3380','MATH2410');

INSERT INTO PREREQUISITE VALUES ('CS3320','CS1310');


COMMIT;

DESC STUDENT;
DESC COURSE;
DESC SECTION;
DESC GRADE_REPORT;
DESC PREREQUISITE;

SELECT *FROM tab;
SELECT TABLE_NAME
FROM USER_TABLES;
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SECTION;
SELECT * FROM GRADE_REPORT;
SELECT * FROM PREREQUISITE;

DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE SECTION;
DROP TABLE GRADE_REPORT;
DROP TABLE PREREQUISITE;

CREATE TABLE STUDENT (
    Name VARCHAR2(30),
    Student_number NUMBER PRIMARY KEY,
    Class NUMBER,
    Major VARCHAR2(20)
);

CREATE TABLE COURSE (
    Course_name VARCHAR2(50),
    Course_number VARCHAR2(10) PRIMARY KEY,
    Credit_hours NUMBER NOT NULL,
    Department VARCHAR2(20)
);

CREATE TABLE SECTION (
    Section_identifier NUMBER PRIMARY KEY,
    Course_number VARCHAR2(10),
    Semester VARCHAR2(20) NOT NULL,
    Year NUMBER,
    Instructor VARCHAR2(30)
);

CREATE TABLE GRADE_REPORT (
    Student_number NUMBER,
    Section_identifier NUMBER,
    Grade CHAR(1) NOT NULL,
    PRIMARY KEY (Student_number, Section_identifier),
    FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number),
    FOREIGN KEY (Section_identifier) REFERENCES SECTION(Section_identifier)
);

CREATE TABLE PREREQUISITE (
    Course_number VARCHAR2(10),
    Prerequisite_number VARCHAR2(10),
    PRIMARY KEY (Course_number, Prerequisite_number),
    FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number)
);

DESC STUDENT;
DESC COURSE;
DESC SECTION;
DESC GRADE_REPORT;
DESC PREREQUISITE;
INSERT INTO STUDENT VALUES ('Smith',17,1,'CS');
INSERT INTO STUDENT VALUES ('Brown',8,2,'CS');

INSERT INTO COURSE VALUES ('Intro to Computer Science','CS1310',4,'CS');
INSERT INTO COURSE VALUES ('Data Structures','CS3320',4,'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics','MATH2410',3,'MATH');
INSERT INTO COURSE VALUES ('Database','CS3380',3,'CS');

INSERT INTO SECTION VALUES (85,'MATH2410','Fall',7,'King');
INSERT INTO SECTION VALUES (92,'CS1310','Fall',7,'Anderson');
INSERT INTO SECTION VALUES (102,'CS3320','Spring',8,'Knuth');
INSERT INTO SECTION VALUES (112,'MATH2410','Fall',8,'Chang');
INSERT INTO SECTION VALUES (119,'CS1310','Fall',8,'Anderson');
INSERT INTO SECTION VALUES (135,'CS3380','Fall',8,'Stone');

INSERT INTO GRADE_REPORT VALUES (17,112,'B');
INSERT INTO GRADE_REPORT VALUES (17,119,'C');
INSERT INTO GRADE_REPORT VALUES (8,85,'A');
INSERT INTO GRADE_REPORT VALUES (8,92,'A');
INSERT INTO GRADE_REPORT VALUES (8,102,'B');
INSERT INTO GRADE_REPORT VALUES (8,135,'A');

INSERT INTO PREREQUISITE VALUES ('CS3380','CS3320');
INSERT INTO PREREQUISITE VALUES ('CS3380','MATH2410');
INSERT INTO PREREQUISITE VALUES ('CS3320','CS1310');

COMMIT;
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SECTION;
SELECT * FROM GRADE_REPORT;
SELECT * FROM PREREQUISITE;
ALTER TABLE STUDENT
ADD Branch VARCHAR2(20);

DESC STUDENT;
UPDATE STUDENT
SET Branch = Major;

SELECT * FROM STUDENT;
ALTER TABLE STUDENT
DROP COLUMN Major;

DESC STUDENT;
SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PREREQUISITE'
AND CONSTRAINT_TYPE = 'R';
ALTER TABLE PREREQUISITE
DROP CONSTRAINT SYS_C008;
ALTER TABLE COURSE
RENAME COLUMN Course_number TO CID;
DESC COURSE;

UPDATE COURSE
SET Credit_hours = 4
WHERE Course_name = 'Database';

SELECT * FROM COURSE;

ALTER TABLE STUDENT
MODIFY Branch VARCHAR2(20) NOT NULL;

DESC STUDENT;
RENAME STUDENT TO PUPIL;
DESC PUPIL;
DROP TABLE PUPIL;

DELETE FROM SECTION
WHERE Semester = 'Fall';

COMMIT;

SELECT * FROM SECTION;

DELETE FROM COURSE
WHERE Course_name = 'Data Structures';

COMMIT;

SELECT * FROM COURSE;

TRUNCATE TABLE GRADE_REPORT;
TRUNCATE TABLE PREREQUISITE;
TRUNCATE TABLE PUPIL;
TRUNCATE TABLE SECTION;
TRUNCATE TABLE COURSE;

DROP TABLE PUPIL;
DROP TABLE COURSE;
DROP TABLE SECTION;

DROP TABLE GRADE_REPORT PURGE;
DROP TABLE PREREQUISITE PURGE;