CREATE TABLE DEPT
(
    DNO NUMBER,
    DNAME VARCHAR2(30)
);
ALTER TABLE DEPT
ADD CONSTRAINT PK_DEPT PRIMARY KEY (DNO);

ALTER TABLE DEPT
MODIFY DNAME NOT NULL;
CREATE TABLE STUDENT4
(
    SID NUMBER,
    SNAME VARCHAR2(30),
    DID NUMBER
);
ALTER TABLE STUDENT4
ADD CONSTRAINT PK_STUDENT4 PRIMARY KEY (SID);

ALTER TABLE STUDENT4
MODIFY SNAME NOT NULL;

ALTER TABLE STUDENT4
ADD CONSTRAINT FK_STUDENT4_DEPT
FOREIGN KEY (DID)
REFERENCES DEPT(DNO);


DESC STUDENT4;

INSERT INTO DEPT VALUES (10, 'CSE');
INSERT INTO DEPT VALUES (20, 'ME');
INSERT INTO DEPT VALUES (30, 'CE');
INSERT INTO DEPT VALUES (40, 'EEE');
INSERT INTO DEPT VALUES (50, 'ECE');
INSERT INTO DEPT VALUES (60, 'CSM');
INSERT INTO DEPT VALUES (70, 'CSD');

COMMIT;
INSERT INTO STUDENT4 VALUES (101, 'Rahul', 10);
INSERT INTO STUDENT4 VALUES (102, 'Sneha', 20);
INSERT INTO STUDENT4 VALUES (103, 'Arjun', 30);
INSERT INTO STUDENT4 VALUES (104, 'Priya', 40);
INSERT INTO STUDENT4 VALUES (105, 'Kiran', 50);
INSERT INTO STUDENT4 VALUES (106, 'Nikhil', 60);
INSERT INTO STUDENT4 VALUES (107, 'Anu', 70);
INSERT INTO STUDENT4 VALUES (108, 'Ravi', 10);
INSERT INTO STUDENT4 VALUES (109, 'Meena', 20);
INSERT INTO STUDENT4 VALUES (110, 'Suresh', 30);

COMMIT;
SELECT S.SID, S.SNAME, S.DID, D.DNAME
FROM STUDENT4 S
JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, D.DNO, D.DNAME
FROM STUDENT4 S
INNER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, D.DNO, D.DNAME
FROM STUDENT4 S
JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNAME
FROM STUDENT4 S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNAME
FROM STUDENT4 S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNAME
FROM STUDENT4 S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
LEFT OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
RIGHT OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID, S.SNAME, S.DID, D.DNO, D.DNAME
FROM STUDENT4 S
FULL OUTER JOIN DEPT D
ON S.DID > D.DNO;

SELECT S.SID, S.SNAME, D.DNO, D.DNAME
FROM STUDENT4 S
CROSS JOIN DEPT D;

SELECT S.SID, S.SNAME, D.DNAME
FROM STUDENT4 S
INNER JOIN DEPT D
ON S.DID = D.DNO;
SELECT S.SID, S.SNAME, D.DNAME
FROM STUDENT4 S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;
SELECT S.SID, S.SNAME, D.DNAME
FROM STUDENT4 S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;
SELECT S.SID, S.SNAME, D.DNAME
FROM STUDENT4 S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;
SELECT S.SID, S.SNAME, D.DNO, D.DNAME
FROM STUDENT4 S
CROSS JOIN DEPT D;